Add None as initial value to api_key to fix type hints
Removing the type ignore clause caused:
ctl/infrahub_ctl/config.py:75: error: Missing named argument "api_key" for "Settings"  [call-arg]