fix(backend): ignore prefect typing errors
Prefect 3.1.15 introduced a change that breaks mypy with
error: Incompatible types in "await" (actual type "State[Coroutine[Any, Any, None]]", expected type
"Awaitable[Any]")  [misc]

Signed-off-by: Fatih Acar <fatih@opsmill.com>